language: php
php:
- 7.1
- 7.2
- 7.3
- 7.4
matrix:
  include:
    - php: 7.1
      script:
      - php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
      after_script:
      - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
    - php: 7.3
      script:
      - composer test-cs
      - composer test-md
      - composer test-cs-fixer
before_script:
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-dist
script:
- php vendor/bin/phpunit
